// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/ovncontroller/proto/ovncontroller.proto

package ovncontroller

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "global/global_proto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LRouterRequest struct {
	RouterName           string         `protobuf:"bytes,1,opt,name=RouterName,proto3" json:"RouterName,omitempty"`
	Ovn                  *OvnController `protobuf:"bytes,2,opt,name=ovn,proto3" json:"ovn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LRouterRequest) Reset()         { *m = LRouterRequest{} }
func (m *LRouterRequest) String() string { return proto.CompactTextString(m) }
func (*LRouterRequest) ProtoMessage()    {}
func (*LRouterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{0}
}

func (m *LRouterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LRouterRequest.Unmarshal(m, b)
}
func (m *LRouterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LRouterRequest.Marshal(b, m, deterministic)
}
func (m *LRouterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LRouterRequest.Merge(m, src)
}
func (m *LRouterRequest) XXX_Size() int {
	return xxx_messageInfo_LRouterRequest.Size(m)
}
func (m *LRouterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LRouterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LRouterRequest proto.InternalMessageInfo

func (m *LRouterRequest) GetRouterName() string {
	if m != nil {
		return m.RouterName
	}
	return ""
}

func (m *LRouterRequest) GetOvn() *OvnController {
	if m != nil {
		return m.Ovn
	}
	return nil
}

type OvnController struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OvnController) Reset()         { *m = OvnController{} }
func (m *OvnController) String() string { return proto.CompactTextString(m) }
func (*OvnController) ProtoMessage()    {}
func (*OvnController) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{1}
}

func (m *OvnController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OvnController.Unmarshal(m, b)
}
func (m *OvnController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OvnController.Marshal(b, m, deterministic)
}
func (m *OvnController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OvnController.Merge(m, src)
}
func (m *OvnController) XXX_Size() int {
	return xxx_messageInfo_OvnController.Size(m)
}
func (m *OvnController) XXX_DiscardUnknown() {
	xxx_messageInfo_OvnController.DiscardUnknown(m)
}

var xxx_messageInfo_OvnController proto.InternalMessageInfo

func (m *OvnController) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LSwitchRequest struct {
	SwitchName           string         `protobuf:"bytes,1,opt,name=SwitchName,proto3" json:"SwitchName,omitempty"`
	Ovn                  *OvnController `protobuf:"bytes,2,opt,name=ovn,proto3" json:"ovn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LSwitchRequest) Reset()         { *m = LSwitchRequest{} }
func (m *LSwitchRequest) String() string { return proto.CompactTextString(m) }
func (*LSwitchRequest) ProtoMessage()    {}
func (*LSwitchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{2}
}

func (m *LSwitchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LSwitchRequest.Unmarshal(m, b)
}
func (m *LSwitchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LSwitchRequest.Marshal(b, m, deterministic)
}
func (m *LSwitchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSwitchRequest.Merge(m, src)
}
func (m *LSwitchRequest) XXX_Size() int {
	return xxx_messageInfo_LSwitchRequest.Size(m)
}
func (m *LSwitchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LSwitchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LSwitchRequest proto.InternalMessageInfo

func (m *LSwitchRequest) GetSwitchName() string {
	if m != nil {
		return m.SwitchName
	}
	return ""
}

func (m *LSwitchRequest) GetOvn() *OvnController {
	if m != nil {
		return m.Ovn
	}
	return nil
}

type LSwitchGetterResponse struct {
	P                    []*LSwitch `protobuf:"bytes,1,rep,name=p,proto3" json:"p,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LSwitchGetterResponse) Reset()         { *m = LSwitchGetterResponse{} }
func (m *LSwitchGetterResponse) String() string { return proto.CompactTextString(m) }
func (*LSwitchGetterResponse) ProtoMessage()    {}
func (*LSwitchGetterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{3}
}

func (m *LSwitchGetterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LSwitchGetterResponse.Unmarshal(m, b)
}
func (m *LSwitchGetterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LSwitchGetterResponse.Marshal(b, m, deterministic)
}
func (m *LSwitchGetterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSwitchGetterResponse.Merge(m, src)
}
func (m *LSwitchGetterResponse) XXX_Size() int {
	return xxx_messageInfo_LSwitchGetterResponse.Size(m)
}
func (m *LSwitchGetterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LSwitchGetterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LSwitchGetterResponse proto.InternalMessageInfo

func (m *LSwitchGetterResponse) GetP() []*LSwitch {
	if m != nil {
		return m.P
	}
	return nil
}

type LRouterGetterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LRouterGetterResponse) Reset()         { *m = LRouterGetterResponse{} }
func (m *LRouterGetterResponse) String() string { return proto.CompactTextString(m) }
func (*LRouterGetterResponse) ProtoMessage()    {}
func (*LRouterGetterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{4}
}

func (m *LRouterGetterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LRouterGetterResponse.Unmarshal(m, b)
}
func (m *LRouterGetterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LRouterGetterResponse.Marshal(b, m, deterministic)
}
func (m *LRouterGetterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LRouterGetterResponse.Merge(m, src)
}
func (m *LRouterGetterResponse) XXX_Size() int {
	return xxx_messageInfo_LRouterGetterResponse.Size(m)
}
func (m *LRouterGetterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LRouterGetterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LRouterGetterResponse proto.InternalMessageInfo

type LSwitch struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	P                    []*LSPort `protobuf:"bytes,2,rep,name=p,proto3" json:"p,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LSwitch) Reset()         { *m = LSwitch{} }
func (m *LSwitch) String() string { return proto.CompactTextString(m) }
func (*LSwitch) ProtoMessage()    {}
func (*LSwitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{5}
}

func (m *LSwitch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LSwitch.Unmarshal(m, b)
}
func (m *LSwitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LSwitch.Marshal(b, m, deterministic)
}
func (m *LSwitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSwitch.Merge(m, src)
}
func (m *LSwitch) XXX_Size() int {
	return xxx_messageInfo_LSwitch.Size(m)
}
func (m *LSwitch) XXX_DiscardUnknown() {
	xxx_messageInfo_LSwitch.DiscardUnknown(m)
}

var xxx_messageInfo_LSwitch proto.InternalMessageInfo

func (m *LSwitch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LSwitch) GetP() []*LSPort {
	if m != nil {
		return m.P
	}
	return nil
}

type LSPort struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LSPort) Reset()         { *m = LSPort{} }
func (m *LSPort) String() string { return proto.CompactTextString(m) }
func (*LSPort) ProtoMessage()    {}
func (*LSPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{6}
}

func (m *LSPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LSPort.Unmarshal(m, b)
}
func (m *LSPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LSPort.Marshal(b, m, deterministic)
}
func (m *LSPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSPort.Merge(m, src)
}
func (m *LSPort) XXX_Size() int {
	return xxx_messageInfo_LSPort.Size(m)
}
func (m *LSPort) XXX_DiscardUnknown() {
	xxx_messageInfo_LSPort.DiscardUnknown(m)
}

var xxx_messageInfo_LSPort proto.InternalMessageInfo

func (m *LSPort) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LRouter struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	P                    []*LRPort `protobuf:"bytes,2,rep,name=p,proto3" json:"p,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LRouter) Reset()         { *m = LRouter{} }
func (m *LRouter) String() string { return proto.CompactTextString(m) }
func (*LRouter) ProtoMessage()    {}
func (*LRouter) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{7}
}

func (m *LRouter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LRouter.Unmarshal(m, b)
}
func (m *LRouter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LRouter.Marshal(b, m, deterministic)
}
func (m *LRouter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LRouter.Merge(m, src)
}
func (m *LRouter) XXX_Size() int {
	return xxx_messageInfo_LRouter.Size(m)
}
func (m *LRouter) XXX_DiscardUnknown() {
	xxx_messageInfo_LRouter.DiscardUnknown(m)
}

var xxx_messageInfo_LRouter proto.InternalMessageInfo

func (m *LRouter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LRouter) GetP() []*LRPort {
	if m != nil {
		return m.P
	}
	return nil
}

type LRPort struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LRPort) Reset()         { *m = LRPort{} }
func (m *LRPort) String() string { return proto.CompactTextString(m) }
func (*LRPort) ProtoMessage()    {}
func (*LRPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_92154015ddb41cc0, []int{8}
}

func (m *LRPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LRPort.Unmarshal(m, b)
}
func (m *LRPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LRPort.Marshal(b, m, deterministic)
}
func (m *LRPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LRPort.Merge(m, src)
}
func (m *LRPort) XXX_Size() int {
	return xxx_messageInfo_LRPort.Size(m)
}
func (m *LRPort) XXX_DiscardUnknown() {
	xxx_messageInfo_LRPort.DiscardUnknown(m)
}

var xxx_messageInfo_LRPort proto.InternalMessageInfo

func (m *LRPort) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*LRouterRequest)(nil), "ovncontroller.LRouterRequest")
	proto.RegisterType((*OvnController)(nil), "ovncontroller.OvnController")
	proto.RegisterType((*LSwitchRequest)(nil), "ovncontroller.LSwitchRequest")
	proto.RegisterType((*LSwitchGetterResponse)(nil), "ovncontroller.LSwitchGetterResponse")
	proto.RegisterType((*LRouterGetterResponse)(nil), "ovncontroller.LRouterGetterResponse")
	proto.RegisterType((*LSwitch)(nil), "ovncontroller.LSwitch")
	proto.RegisterType((*LSPort)(nil), "ovncontroller.LSPort")
	proto.RegisterType((*LRouter)(nil), "ovncontroller.LRouter")
	proto.RegisterType((*LRPort)(nil), "ovncontroller.LRPort")
}

func init() {
	proto.RegisterFile("srv/ovncontroller/proto/ovncontroller.proto", fileDescriptor_92154015ddb41cc0)
}

var fileDescriptor_92154015ddb41cc0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5f, 0x4b, 0x3a, 0x41,
	0x14, 0xfd, 0xad, 0xfe, 0x30, 0xba, 0x62, 0xc8, 0x98, 0x25, 0x62, 0x21, 0xab, 0x84, 0x10, 0xac,
	0x60, 0xcf, 0x3d, 0x58, 0x84, 0x05, 0xf6, 0x87, 0xed, 0x39, 0x4a, 0xd7, 0xd1, 0x16, 0xb6, 0xb9,
	0xdb, 0xee, 0xb8, 0xd1, 0x07, 0xe8, 0x7b, 0xc7, 0xee, 0xdd, 0x6a, 0x46, 0x57, 0xc4, 0x7a, 0xd1,
	0x9d, 0x73, 0xe7, 0x9e, 0x73, 0xee, 0x99, 0xd9, 0x85, 0xe3, 0x30, 0x88, 0xba, 0x18, 0x09, 0x07,
	0x85, 0x0c, 0xd0, 0xf3, 0x78, 0xd0, 0xf5, 0x03, 0x94, 0xa8, 0x63, 0x56, 0x82, 0xb1, 0x92, 0x06,
	0xd6, 0x8f, 0x66, 0x1e, 0x8e, 0x47, 0x5e, 0x97, 0xfe, 0x1e, 0xa9, 0x8f, 0x7e, 0x09, 0xa2, 0x36,
	0xf3, 0x09, 0x76, 0x86, 0x36, 0xce, 0x25, 0x0f, 0x6c, 0xfe, 0x3a, 0xe7, 0xa1, 0x64, 0x87, 0x00,
	0x04, 0xdc, 0x8c, 0x5e, 0x78, 0xcd, 0x68, 0x1a, 0x9d, 0x6d, 0x5b, 0x41, 0x98, 0x05, 0x79, 0x8c,
	0x44, 0x2d, 0xd7, 0x34, 0x3a, 0xc5, 0x5e, 0xc3, 0xd2, 0xbd, 0xdc, 0x46, 0xe2, 0xfc, 0x7b, 0x65,
	0xc7, 0x1b, 0xcd, 0x16, 0x94, 0x34, 0x94, 0x31, 0xf8, 0xaf, 0x50, 0x27, 0xcf, 0x89, 0x8d, 0xfb,
	0x37, 0x57, 0x3a, 0xcf, 0x8a, 0x0d, 0x02, 0x54, 0x1b, 0x3f, 0xc8, 0xc6, 0x36, 0x4e, 0xa1, 0x9a,
	0x2a, 0x0c, 0xb8, 0x4c, 0xc6, 0x0d, 0x7d, 0x14, 0x21, 0x67, 0x6d, 0x30, 0xfc, 0x9a, 0xd1, 0xcc,
	0x77, 0x8a, 0xbd, 0xbd, 0x05, 0x9a, 0x2f, 0x4b, 0x86, 0x6f, 0xee, 0x43, 0x35, 0xcd, 0x49, 0x6f,
	0x37, 0xcf, 0x60, 0x2b, 0xdd, 0x96, 0x35, 0x18, 0x6b, 0xc5, 0xec, 0xb9, 0x84, 0xbd, 0xba, 0xc4,
	0x7e, 0x87, 0x81, 0x8c, 0xc9, 0x1b, 0x50, 0xa0, 0x45, 0x66, 0x36, 0xb1, 0x02, 0x49, 0x6f, 0xac,
	0x60, 0xab, 0x0a, 0xf6, 0x2a, 0x85, 0xde, 0x47, 0x0e, 0x2a, 0x43, 0x9c, 0xb9, 0xce, 0xc8, 0xa3,
	0x51, 0xfa, 0x8e, 0x74, 0x51, 0xb0, 0x07, 0xd8, 0x1d, 0x70, 0xa9, 0x55, 0xae, 0xc4, 0x14, 0xd9,
	0xc1, 0x8a, 0x9c, 0xe8, 0xe8, 0xea, 0xed, 0xec, 0xf2, 0x42, 0x70, 0xff, 0xd8, 0x25, 0x54, 0xae,
	0x71, 0xe2, 0x4e, 0xdf, 0x35, 0x85, 0x75, 0xec, 0x65, 0x2b, 0xbd, 0xc0, 0x0a, 0xd3, 0x05, 0x94,
	0xfb, 0x93, 0xc9, 0x5f, 0x69, 0xd4, 0x1c, 0x28, 0xf0, 0xac, 0x1c, 0xa8, 0x92, 0x9d, 0x83, 0xf6,
	0x26, 0x2d, 0xe7, 0x90, 0x79, 0x81, 0x96, 0x73, 0x48, 0x0f, 0x7b, 0x0d, 0xfb, 0xda, 0x1c, 0x7e,
	0x4d, 0x33, 0x2e, 0x24, 0xdf, 0x86, 0x93, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x87, 0x13,
	0xb8, 0x81, 0x04, 0x00, 0x00,
}
