// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/appnetwork/proto/appnetwork.proto

package appnetwork

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "global/global_proto/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for QosService service

type QosService interface {
	GetQos(ctx context.Context, in *proto1.Empty, opts ...client.CallOption) (*QosGetterResponse, error)
	DelQos(ctx context.Context, in *QosStruc, opts ...client.CallOption) (*proto1.Response, error)
}

type qosService struct {
	c    client.Client
	name string
}

func NewQosService(name string, c client.Client) QosService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "qosservice"
	}
	return &qosService{
		c:    c,
		name: name,
	}
}

func (c *qosService) GetQos(ctx context.Context, in *proto1.Empty, opts ...client.CallOption) (*QosGetterResponse, error) {
	req := c.c.NewRequest(c.name, "QosService.GetQos", in)
	out := new(QosGetterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qosService) DelQos(ctx context.Context, in *QosStruc, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "QosService.DelQos", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QosService service

type QosServiceHandler interface {
	GetQos(context.Context, *proto1.Empty, *QosGetterResponse) error
	DelQos(context.Context, *QosStruc, *proto1.Response) error
}

func RegisterQosServiceHandler(s server.Server, hdlr QosServiceHandler, opts ...server.HandlerOption) error {
	type qosService interface {
		GetQos(ctx context.Context, in *proto1.Empty, out *QosGetterResponse) error
		DelQos(ctx context.Context, in *QosStruc, out *proto1.Response) error
	}
	type QosService struct {
		qosService
	}
	h := &qosServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&QosService{h}, opts...))
}

type qosServiceHandler struct {
	QosServiceHandler
}

func (h *qosServiceHandler) GetQos(ctx context.Context, in *proto1.Empty, out *QosGetterResponse) error {
	return h.QosServiceHandler.GetQos(ctx, in, out)
}

func (h *qosServiceHandler) DelQos(ctx context.Context, in *QosStruc, out *proto1.Response) error {
	return h.QosServiceHandler.DelQos(ctx, in, out)
}
