// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/appnetwork/proto/appnetwork.proto

package appnetwork

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "global/global_proto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QosStruc struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QosStruc) Reset()         { *m = QosStruc{} }
func (m *QosStruc) String() string { return proto.CompactTextString(m) }
func (*QosStruc) ProtoMessage()    {}
func (*QosStruc) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bcae7c0c650410, []int{0}
}

func (m *QosStruc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QosStruc.Unmarshal(m, b)
}
func (m *QosStruc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QosStruc.Marshal(b, m, deterministic)
}
func (m *QosStruc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QosStruc.Merge(m, src)
}
func (m *QosStruc) XXX_Size() int {
	return xxx_messageInfo_QosStruc.Size(m)
}
func (m *QosStruc) XXX_DiscardUnknown() {
	xxx_messageInfo_QosStruc.DiscardUnknown(m)
}

var xxx_messageInfo_QosStruc proto.InternalMessageInfo

type QosGetterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QosGetterResponse) Reset()         { *m = QosGetterResponse{} }
func (m *QosGetterResponse) String() string { return proto.CompactTextString(m) }
func (*QosGetterResponse) ProtoMessage()    {}
func (*QosGetterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bcae7c0c650410, []int{1}
}

func (m *QosGetterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QosGetterResponse.Unmarshal(m, b)
}
func (m *QosGetterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QosGetterResponse.Marshal(b, m, deterministic)
}
func (m *QosGetterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QosGetterResponse.Merge(m, src)
}
func (m *QosGetterResponse) XXX_Size() int {
	return xxx_messageInfo_QosGetterResponse.Size(m)
}
func (m *QosGetterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QosGetterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QosGetterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QosStruc)(nil), "QosStruc")
	proto.RegisterType((*QosGetterResponse)(nil), "QosGetterResponse")
}

func init() {
	proto.RegisterFile("srv/appnetwork/proto/appnetwork.proto", fileDescriptor_b0bcae7c0c650410)
}

var fileDescriptor_b0bcae7c0c650410 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x2e, 0x2a, 0xd3,
	0x4f, 0x2c, 0x28, 0xc8, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0x47, 0x12, 0xd0, 0x03, 0x0b, 0x48, 0xa9, 0xa5, 0xe7, 0xe4, 0x27, 0x25, 0xe6, 0xe8, 0x43, 0xa8,
	0x78, 0x88, 0x2a, 0x08, 0x09, 0x11, 0x82, 0xa8, 0x53, 0xe2, 0xe2, 0xe2, 0x08, 0xcc, 0x2f, 0x0e,
	0x2e, 0x29, 0x2a, 0x4d, 0x56, 0x12, 0xe6, 0x12, 0x0c, 0xcc, 0x2f, 0x76, 0x4f, 0x2d, 0x29, 0x49,
	0x2d, 0x0a, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x35, 0x4a, 0xe1, 0xe2, 0x02, 0x29, 0x48,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2, 0xe5, 0x62, 0x73, 0x4f, 0x2d, 0x09, 0xcc, 0x2f, 0x16,
	0xe2, 0xd5, 0x83, 0x9a, 0xe3, 0x9a, 0x5b, 0x50, 0x52, 0x29, 0x25, 0xa4, 0x87, 0xa1, 0x55, 0x89,
	0x41, 0x48, 0x9d, 0x8b, 0xcd, 0x25, 0x35, 0x07, 0xa4, 0x9c, 0x53, 0x0f, 0x66, 0x8d, 0x94, 0x00,
	0x4c, 0x27, 0x42, 0x61, 0x12, 0x1b, 0xd8, 0x35, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e,
	0x11, 0x2f, 0x06, 0xde, 0x00, 0x00, 0x00,
}
