// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/ovs/proto/ovs.proto

package ovs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "global/global_proto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Parameter struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a06f610ef4b9809, []int{0}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Netflow struct {
	Server               []string     `protobuf:"bytes,1,rep,name=server,proto3" json:"server,omitempty"`
	Client               []string     `protobuf:"bytes,2,rep,name=client,proto3" json:"client,omitempty"`
	Parameter            []*Parameter `protobuf:"bytes,3,rep,name=parameter,proto3" json:"parameter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Netflow) Reset()         { *m = Netflow{} }
func (m *Netflow) String() string { return proto.CompactTextString(m) }
func (*Netflow) ProtoMessage()    {}
func (*Netflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a06f610ef4b9809, []int{1}
}

func (m *Netflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Netflow.Unmarshal(m, b)
}
func (m *Netflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Netflow.Marshal(b, m, deterministic)
}
func (m *Netflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Netflow.Merge(m, src)
}
func (m *Netflow) XXX_Size() int {
	return xxx_messageInfo_Netflow.Size(m)
}
func (m *Netflow) XXX_DiscardUnknown() {
	xxx_messageInfo_Netflow.DiscardUnknown(m)
}

var xxx_messageInfo_Netflow proto.InternalMessageInfo

func (m *Netflow) GetServer() []string {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *Netflow) GetClient() []string {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Netflow) GetParameter() []*Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameter)(nil), "Parameter")
	proto.RegisterType((*Netflow)(nil), "Netflow")
}

func init() { proto.RegisterFile("api/ovs/proto/ovs.proto", fileDescriptor_0a06f610ef4b9809) }

var fileDescriptor_0a06f610ef4b9809 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xd1, 0x4a, 0x04, 0x21,
	0x14, 0x86, 0x9b, 0xb5, 0xb6, 0x3c, 0xdd, 0x84, 0x44, 0xc9, 0x5e, 0x0d, 0x73, 0x11, 0xd2, 0x85,
	0x43, 0x1b, 0x3d, 0x40, 0x2f, 0x50, 0xe1, 0x0b, 0x84, 0xbb, 0x7b, 0x8a, 0x01, 0x1b, 0x45, 0xcd,
	0xe8, 0xed, 0x63, 0x3c, 0x33, 0xed, 0x8d, 0x7e, 0xff, 0x77, 0x84, 0xe3, 0x0f, 0xb7, 0x36, 0x0c,
	0xbd, 0x2f, 0xa9, 0x0f, 0xd1, 0x67, 0x3f, 0x91, 0xae, 0xb4, 0xb9, 0xfb, 0x74, 0x7e, 0x67, 0x5d,
	0x4f, 0xd7, 0x3b, 0x8d, 0xe9, 0x24, 0x45, 0xef, 0xba, 0x27, 0xe0, 0x6f, 0x36, 0xda, 0x2f, 0xcc,
	0x18, 0x85, 0x80, 0xd3, 0xfc, 0x1b, 0x50, 0x36, 0x6d, 0xa3, 0xb8, 0xa9, 0x2c, 0xae, 0xe1, 0xac,
	0x58, 0xf7, 0x8d, 0x72, 0x55, 0x25, 0x85, 0x6e, 0x0f, 0xe7, 0x2f, 0x98, 0x3f, 0x9c, 0xff, 0x11,
	0x37, 0xb0, 0x4e, 0x18, 0x0b, 0x46, 0xd9, 0xb4, 0x4c, 0x71, 0x33, 0xa7, 0xc9, 0xef, 0xdd, 0x80,
	0x63, 0x96, 0x2b, 0xf2, 0x94, 0x84, 0x02, 0x1e, 0x96, 0x8d, 0x92, 0xb5, 0x4c, 0x5d, 0x6e, 0x41,
	0xff, 0xff, 0xc1, 0x1c, 0x87, 0xdb, 0x07, 0x60, 0xaf, 0x25, 0x89, 0x7b, 0x80, 0xe7, 0xc3, 0x61,
	0x59, 0x77, 0xa1, 0x67, 0xda, 0x5c, 0xe9, 0xb9, 0x89, 0xc1, 0x14, 0xfc, 0x98, 0xb0, 0x3b, 0xd9,
	0xad, 0x6b, 0xab, 0xc7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xf4, 0x50, 0xba, 0x18, 0x01,
	0x00, 0x00,
}
