// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/appmail/proto/appmail.proto

package appmail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("srv/appmail/proto/appmail.proto", fileDescriptor_a30f54ac2b01f21c) }

var fileDescriptor_a30f54ac2b01f21c = []byte{
	// 52 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x2e, 0x2a, 0xd3,
	0x4f, 0x2c, 0x28, 0xc8, 0x4d, 0xcc, 0xcc, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0xf1, 0xf4,
	0xc0, 0xbc, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x24, 0xb3, 0xfd, 0xc3,
	0x29, 0x00, 0x00, 0x00,
}
