// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/appmanage/proto/appaction.proto

package appaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "global/global_proto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlaceHolder struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceHolder) Reset()         { *m = PlaceHolder{} }
func (m *PlaceHolder) String() string { return proto.CompactTextString(m) }
func (*PlaceHolder) ProtoMessage()    {}
func (*PlaceHolder) Descriptor() ([]byte, []int) {
	return fileDescriptor_999ee9565b46346a, []int{0}
}

func (m *PlaceHolder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceHolder.Unmarshal(m, b)
}
func (m *PlaceHolder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceHolder.Marshal(b, m, deterministic)
}
func (m *PlaceHolder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceHolder.Merge(m, src)
}
func (m *PlaceHolder) XXX_Size() int {
	return xxx_messageInfo_PlaceHolder.Size(m)
}
func (m *PlaceHolder) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceHolder.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceHolder proto.InternalMessageInfo

type AppObject struct {
	AppId                string   `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	AppType              string   `protobuf:"bytes,3,opt,name=AppType,proto3" json:"AppType,omitempty"`
	AppStatus            int32    `protobuf:"varint,4,opt,name=AppStatus,proto3" json:"AppStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppObject) Reset()         { *m = AppObject{} }
func (m *AppObject) String() string { return proto.CompactTextString(m) }
func (*AppObject) ProtoMessage()    {}
func (*AppObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_999ee9565b46346a, []int{1}
}

func (m *AppObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppObject.Unmarshal(m, b)
}
func (m *AppObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppObject.Marshal(b, m, deterministic)
}
func (m *AppObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppObject.Merge(m, src)
}
func (m *AppObject) XXX_Size() int {
	return xxx_messageInfo_AppObject.Size(m)
}
func (m *AppObject) XXX_DiscardUnknown() {
	xxx_messageInfo_AppObject.DiscardUnknown(m)
}

var xxx_messageInfo_AppObject proto.InternalMessageInfo

func (m *AppObject) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AppObject) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppObject) GetAppType() string {
	if m != nil {
		return m.AppType
	}
	return ""
}

func (m *AppObject) GetAppStatus() int32 {
	if m != nil {
		return m.AppStatus
	}
	return 0
}

type AppListResponse struct {
	Ao                   []*AppObject `protobuf:"bytes,1,rep,name=ao,proto3" json:"ao,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AppListResponse) Reset()         { *m = AppListResponse{} }
func (m *AppListResponse) String() string { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()    {}
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_999ee9565b46346a, []int{2}
}

func (m *AppListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListResponse.Unmarshal(m, b)
}
func (m *AppListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListResponse.Marshal(b, m, deterministic)
}
func (m *AppListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListResponse.Merge(m, src)
}
func (m *AppListResponse) XXX_Size() int {
	return xxx_messageInfo_AppListResponse.Size(m)
}
func (m *AppListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppListResponse proto.InternalMessageInfo

func (m *AppListResponse) GetAo() []*AppObject {
	if m != nil {
		return m.Ao
	}
	return nil
}

func init() {
	proto.RegisterType((*PlaceHolder)(nil), "PlaceHolder")
	proto.RegisterType((*AppObject)(nil), "AppObject")
	proto.RegisterType((*AppListResponse)(nil), "AppListResponse")
}

func init() {
	proto.RegisterFile("srv/appmanage/proto/appaction.proto", fileDescriptor_999ee9565b46346a)
}

var fileDescriptor_999ee9565b46346a = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xdf, 0x76, 0xef, 0x94, 0x9e, 0x55, 0x36, 0x82, 0x17, 0xa1, 0x78, 0x51, 0x2a, 0x48,
	0x6f, 0x4c, 0x75, 0x7e, 0x82, 0x5c, 0xa9, 0x20, 0x2a, 0x55, 0xaf, 0xe5, 0xb4, 0x0d, 0x63, 0xd2,
	0x35, 0x87, 0x26, 0x0a, 0x7e, 0x1b, 0x3f, 0xaa, 0x2c, 0x99, 0x6b, 0xf1, 0xca, 0x9b, 0x84, 0xdf,
	0x73, 0x9e, 0xf3, 0x17, 0x4e, 0x4d, 0xff, 0x51, 0x20, 0xd1, 0x06, 0x3b, 0x5c, 0xa9, 0x82, 0x7a,
	0x6d, 0xf5, 0x96, 0xb1, 0xb6, 0x6b, 0xdd, 0x09, 0xc7, 0xc9, 0xd9, 0xaa, 0xd5, 0x15, 0xb6, 0x85,
	0xff, 0x5e, 0xbd, 0xc9, 0xbf, 0x5e, 0xf2, 0xbe, 0xec, 0x08, 0x66, 0x8f, 0x2d, 0xd6, 0xea, 0x46,
	0xb7, 0x8d, 0xea, 0x33, 0x03, 0x91, 0x24, 0x7a, 0xa8, 0xde, 0x54, 0x6d, 0xd9, 0x31, 0x4c, 0x25,
	0xd1, 0x6d, 0xc3, 0x83, 0x34, 0xc8, 0xa3, 0xd2, 0x03, 0xe3, 0x70, 0x28, 0x89, 0xee, 0x71, 0xa3,
	0x78, 0xe8, 0xf4, 0x1f, 0xdc, 0x45, 0x9e, 0x3f, 0x49, 0xf1, 0xc9, 0x3e, 0xb2, 0x45, 0x76, 0xe2,
	0xca, 0x3e, 0x59, 0xb4, 0xef, 0x86, 0xff, 0x4f, 0x83, 0x7c, 0x5a, 0x0e, 0x42, 0x76, 0x0e, 0x73,
	0x49, 0x74, 0xb7, 0x36, 0xb6, 0x54, 0x86, 0x74, 0x67, 0x14, 0x4b, 0x20, 0x44, 0xcd, 0x83, 0x74,
	0x92, 0xcf, 0x96, 0x20, 0xf6, 0x23, 0x95, 0x21, 0xea, 0xe5, 0x57, 0x00, 0x11, 0x12, 0x49, 0xb7,
	0x2e, 0xbb, 0x80, 0xf8, 0x5a, 0xd9, 0x61, 0xe8, 0x58, 0x8c, 0xf6, 0x49, 0x16, 0xe2, 0x57, 0xe5,
	0xec, 0x1f, 0xbb, 0x84, 0xf9, 0x0b, 0x35, 0x68, 0xd5, 0x90, 0x34, 0x6a, 0x91, 0x2c, 0xc4, 0xee,
	0x40, 0xa3, 0x14, 0x01, 0xb1, 0x6c, 0x9a, 0x3f, 0xfb, 0xab, 0x03, 0x77, 0xdc, 0xab, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x42, 0xc3, 0x0d, 0x62, 0xab, 0x01, 0x00, 0x00,
}
